#
# These allow for the build to be less verbose
#

ifdef V
  VERBOSE:= $(V)
else
  VERBOSE:= 0
endif

ifeq ($(VERBOSE),1)
define Q
  $(2)
endef
else
define Q
  @echo "	[$1] $(3)"
  @$(2)
endef
endif

%.o : %.S include/asm-offsets.h
	$(call Q,AS, $(CC) $(CPPFLAGS) $(AFLAGS) -c $< -o $@, $@)

%.s : %.S include/asm-offsets.h
	$(call Q,CC, $(CC) $(CPPFLAGS) $(AFLAGS) -E -c $< -o $@, $@)

%.o : %.c
	$(call Q,CC, $(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@, $@)

%.s : %.c
	$(call Q,CC, $(CC) $(CPPFLAGS) $(CFLAGS) -S -c $< -o $@, $@)

%.i : %.c
	$(call Q,CC, $(CC) $(CPPFLAGS) $(CFLAGS) -E -c $< -o $@, $@)

%built-in.o : %
	$(call Q,LD, $(LD) $(LDRFLAGS) -r $^ -o $@, $@)

%.lds : %.lds.S
	$(call Q,CC, $(CC) $(CPPFLAGS) -P -E $< -o $@, $@)
