# -*-Makefile-*-
CORE_TEST := core/test/run-device core/test/run-mem_region core/test/run-malloc core/test/run-malloc-speed core/test/run-mem_region_init core/test/run-mem_region_release_unused core/test/run-mem_region_release_unused_noalloc

check: $(CORE_TEST:%=%-check)

$(CORE_TEST:%=%-check) : %-check: %
	$(VALGRIND) $<

core/test/stubs.o: core/test/stubs.c
	$(HOSTCC) $(HOSTCFLAGS) -g -c -o $@ $<

$(CORE_TEST) : core/test/stubs.o

$(CORE_TEST) : % : %.c 
	$(HOSTCC) $(HOSTCFLAGS) -O0 -g -I include -I . -I libfdt -o $@ $< core/test/stubs.o

clean: core-test-clean

core-test-clean:
	$(RM) core/test/*.o $(CORE_TEST)
